### PR TITLE
Ld cleaning

### PR DESCRIPTION
**Pull request by luke-dowling**
minor changes to file names, variable names and destructing,  still more to do.
updated the way the user is updated, i added a bit of functionality to update the codex at the same time, let me know if this is something you wanted.
added a readme to all page: root, client and server (maybe this would be okay to just have in the root, thoughts?)
added .env to frontend so we can have seperate logins

### CODE REVIEW

**Comment by FunkyDunk-Z** [comment]
before we confirm everything, userModel needs to be changed so that username is set to unique. thats why i was using email or id, cant remember which one, but right now people could have the same username so we need to make sure thats not possible

**Comment by luke-dowling** [comment]
is it because you are going to identified by your username and not your email? all good if so and we can make these unique

**Comment by luke-dowling** [comment]
it looks like it is unique already no?

**Review by FunkyDunk-Z — APPROVED** [review]

**Comment by FunkyDunk-Z** [comment]
yer i just checked and it already was

**Pull request merged**
